[[Project]]
author = "Author"
title = "Title"
date = "\\today"
project_name = "Project1"
template = "Math" #Make sure to have first letter upercased

[[Document]]
paper_size = "letterpaper"
font_size = 11 #font size number
document_class = "article"
packages = []

# Multi project
[[Project]]
author = "Author"
title = "Title"
date = "\\today"
project_name = "Project2"
template = "Beamer" #Make sure to have first letter upercased

[[Document]]
paper_size = "letterpaper"
font_size = 11 #font size number
document_class = "article"
packages = []
