[package]
name = "texcreate"
version = "0.5.3"
edition = "2021"
license = "MIT"
description = "A tool to create TeX projects from LaTeX templates."
author = "Mustafif Khan"
repository = "https://github.com/MKProj/texcreate.git"
homepage = "https://mkproj.com"
github = "https://github.com/MKProj/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
mdbook = "0.4"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
texcreate_lib = "0.1.1"