[Project]
author = "Author"
title = "Title"
date = "\\today"
project_name = "test"
template = "Basic" #Make sure to have first letter upercased

[Document]
paper_size = "letterpaper"
font_size = 12 #font size number
document_class = "article"
packages = ["", ""]