[Project]
author = "Author"
title = "Title"
date = "\today"
project_name = "test"
template = "Book" #Make sure to have first letter upercased

[Document]
paper_size = ""
font_size = 0 #font size number
document_class = ""
packages = ["", ""]