[Project]
author = ""
title = "Title"
date = "\\today"
project_name = "test"
template = "Lalalala" #Make sure to have first letter upercased

[Document]
paper_size = "letterpaper"
font_size = 11 #font size number
document_class = "article"
packages = []
