[Project]
author = 'author'
title = 'title'
date = '\\today'
template = 'Basic'
project_name = 'Project'

[Document]
paper_size = 'letterpaper'
font_size = 11
document_class = 'article'
packages = []
