[package]
name = "texc-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
texc-config = {version = "0.1", path = "../texc-config"}
async-std = "1.10.0"
failure = "0.1"
failure_derive = "0.1"